# Travis Configuration for QuantEcon.py
#
# Thank you for the writeup given by dan-blanchard at https://gist.github.com/dan-blanchard/7045057
#

language: python
python:
  - 3.5


before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  #- sudo rm -rf /dev/shm
  #- sudo ln -s /run/shm /dev/shm

  # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


install:
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform
  - conda install --yes python=$TRAVIS_PYTHON_VERSION ipython numpy scipy nose pandas pip sympy pytables statsmodels numba
    # To Install Full Anaconda Stack (conda install --yes python=$TRAVIS_PYTHON_VERSION anaconda)
  - pip install coveralls coverage
  - python setup.py install

script:
  - nosetests --with-coverage --cover-package=quantecon --exclude=models --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_QuantEcon.py_ecbf2b291e_2
  - python -m properform Push 47.88.50.110:15554 asdf_QuantEcon.py_ecbf2b291e_2 ./profile_QuantEcon.py_ecbf2b291e_2
#quantecon.models excluded from tests to prevent triggering the ImportWarning

after_success:
  - coveralls
 #2017-09-18 12:48:20 modified at 0 #2017-09-18 12:48:25 modified at 1 #2017-09-18 12:48:29 modified at 2